/**
 * Catppuccin Mocha — Bunti preset theme (dark).
 *
 * Converted from the "Catppuccin Mocha" VS Code theme.
 * Source: https://github.com/catppuccin/vscode (MIT license).
 * Vendored theme JSON: scripts/vscode-themes/catppuccin-mocha.json
 *
 * Hand-tuning (applied by the converter, see PRESETS):
 * - accent: activityBarBadge duplicates the mauve primary; use Catppuccin pink
 * - muted auto-derives (descriptionForeground equals foreground); the derived
 * - value lands on overlay1
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import { createTheme, type Theme } from '../theme';

/** Catppuccin Mocha preset theme (dark). */
export const catppuccinMocha: Theme = createTheme({
  name: 'catppuccin-mocha',
  mode: 'dark',
  background: '#1e1e2e',
  surface: '#181825',
  surfaceRaised: '#11111b',
  foreground: '#cdd6f4',
  primary: '#cba6f7',
  onPrimary: '#11111b',
  accent: '#f5c2e7',
  border: '#585b70',
  focus: '#cba6f7',
  selection: '#313244',
  success: '#a6e3a1',
  warning: '#fab387',
  danger: '#f38ba8',
  info: '#89b4fa',
});
