/**
 * Dracula — Bunti preset theme (dark).
 *
 * Converted from the "Dracula" VS Code theme.
 * Source: https://github.com/dracula/visual-studio-code (MIT license).
 * Vendored theme JSON: scripts/vscode-themes/dracula.json
 *
 * Hand-tuning (applied by the converter, see PRESETS):
 * - primary: button.background is the neutral #44475a; use the signature purple
 * - muted/border: #6272a4 is the canonical Dracula comment color
 * - focus: derive from primary (source swaps border/focus prominence)
 * - warning: Dracula sets editorWarning.foreground to its cyan; use its orange
 * - info: source omits editorInfo.foreground; use the Dracula cyan
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import { createTheme, type Theme } from '../theme';

/** Dracula preset theme (dark). */
export const dracula: Theme = createTheme({
  name: 'dracula',
  mode: 'dark',
  background: '#282a36',
  surface: '#21222c',
  surfaceRaised: '#191a21',
  foreground: '#f8f8f2',
  muted: '#6272a4',
  primary: '#bd93f9',
  accent: '#ff79c6',
  border: '#6272a4',
  selection: '#44475a',
  success: '#50fa7b',
  warning: '#ffb86c',
  danger: '#ff5555',
  info: '#8be9fd',
});
