/**
 * GitHub Light — Bunti preset theme (light).
 *
 * Converted from the "GitHub Light" VS Code theme.
 * Source: https://github.com/primer/github-vscode-theme (MIT license).
 * Vendored theme JSON: scripts/vscode-themes/github-light.json
 *
 * Hand-tuning (applied by the converter, see PRESETS):
 * - primary: button.background green sits at ~4.5:1 with white; GitHub's brand
 * - blue is the safer, more recognizable primary
 * - accent: badge.background would duplicate the new primary; use GitHub purple
 * - surfaceRaised: source equals surface; use Primer gray-1
 * - selection: source value composites to near-white; derive a visible one
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import { createTheme, type Theme } from '../theme';

/** GitHub Light preset theme (light). */
export const githubLight: Theme = createTheme({
  name: 'github-light',
  mode: 'light',
  background: '#ffffff',
  surface: '#f6f8fa',
  surfaceRaised: '#eaeef2',
  foreground: '#1f2328',
  muted: '#656d76',
  primary: '#0969da',
  onPrimary: '#ffffff',
  accent: '#8250df',
  border: '#d0d7de',
  focus: '#0969da',
  success: '#116329',
  danger: '#cf222e',
});
