/**
 * Bunti preset themes, converted from popular VS Code themes.
 *
 * import { themes, dracula } from '@zakmandhro/bunti/themes';
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import type { Theme } from '../theme';
import { catppuccinMocha } from './catppuccin-mocha';
import { dracula } from './dracula';
import { githubLight } from './github-light';
import { nord } from './nord';
import { oneDarkPro } from './one-dark-pro';
import { tokyoNight } from './tokyo-night';

export { catppuccinMocha, dracula, githubLight, nord, oneDarkPro, tokyoNight };

/** All preset themes, keyed by slug. */
export const themes: Record<string, Theme> = {
  'catppuccin-mocha': catppuccinMocha,
  dracula,
  'github-light': githubLight,
  nord,
  'one-dark-pro': oneDarkPro,
  'tokyo-night': tokyoNight,
};
