/**
 * Nord — Bunti preset theme (dark).
 *
 * Converted from the "Nord" VS Code theme.
 * Source: https://github.com/nordtheme/visual-studio-code (MIT license).
 * Vendored theme JSON: scripts/vscode-themes/nord.json
 *
 * Hand-tuning (applied by the converter, see PRESETS):
 * - surface/surfaceRaised: source is flat (all #2e3440); use nord1/nord2
 * - border: nord3 so it stays visible on the lifted surfaces
 * - muted: descriptionForeground is 90%-alpha foreground (too bright); derive
 * - selection: source uses bright nord8 as a bg (unreadable under light text); derive
 * - focus: focusBorder is nord1 (invisible); derive from primary
 * - accent: badge colors duplicate the frost primary; use nord15 purple
 * - info: source omits editorInfo.foreground; use nord9 blue
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import { createTheme, type Theme } from '../theme';

/** Nord preset theme (dark). */
export const nord: Theme = createTheme({
  name: 'nord',
  mode: 'dark',
  background: '#2e3440',
  surface: '#3b4252',
  surfaceRaised: '#434c5e',
  foreground: '#d8dee9',
  primary: '#82b7c6',
  onPrimary: '#2e3440',
  accent: '#b48ead',
  border: '#4c566a',
  success: '#a3be8c',
  warning: '#ebcb8b',
  danger: '#bf616a',
  info: '#81a1c1',
});
