/**
 * One Dark Pro — Bunti preset theme (dark).
 *
 * Converted from the "One Dark Pro" VS Code theme.
 * Source: https://github.com/Binaryify/OneDark-Pro (MIT license).
 * Vendored theme JSON: scripts/vscode-themes/one-dark-pro.json
 *
 * Hand-tuning (applied by the converter, see PRESETS):
 * - primary: button.background is the muddy #404754; use the signature blue
 * - accent: activityBarBadge blue is too close to primary; use the purple
 * - info: source omits editorInfo.foreground; use the One Dark cyan
 * - surfaceRaised: source equals surface; use the menu/dropdown shade
 * - focus: focusBorder equals border (invisible); derive from primary
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import { createTheme, type Theme } from '../theme';

/** One Dark Pro preset theme (dark). */
export const oneDarkPro: Theme = createTheme({
  name: 'one-dark-pro',
  mode: 'dark',
  background: '#282c34',
  surface: '#21252b',
  surfaceRaised: '#353b45',
  foreground: '#abb2bf',
  primary: '#61afef',
  accent: '#c678dd',
  border: '#3e4452',
  selection: '#2c313a',
  success: '#8cc265',
  warning: '#d19a66',
  danger: '#c24038',
  info: '#56b6c2',
});
