/**
 * Tokyo Night — Bunti preset theme (dark).
 *
 * Converted from the "Tokyo Night" VS Code theme.
 * Source: https://github.com/tokyo-night/tokyo-night-vscode-theme (MIT license).
 * Vendored theme JSON: scripts/vscode-themes/tokyo-night.json
 *
 * Hand-tuning (applied by the converter, see PRESETS):
 * - muted: descriptionForeground fails 2.5:1; #565f89 is the theme comment color
 * - surfaceRaised: source equals surface; #292e42 is the bg-highlight shade
 * - accent: activityBarBadge duplicates the primary hue; #7aa2f7 is the signature blue
 * - focus: focusBorder is 20% alpha (near-invisible composited); derive from primary
 *
 * Generated by scripts/convert-vscode-theme.ts - do not edit by hand.
 * Regenerate: bun scripts/convert-vscode-theme.ts --presets
 */
import { createTheme, type Theme } from '../theme';

/** Tokyo Night preset theme (dark). */
export const tokyoNight: Theme = createTheme({
  name: 'tokyo-night',
  mode: 'dark',
  background: '#1a1b26',
  surface: '#16161e',
  surfaceRaised: '#292e42',
  foreground: '#a9b1d6',
  muted: '#565f89',
  primary: '#385191',
  onPrimary: '#ffffff',
  accent: '#7aa2f7',
  border: '#101014',
  selection: '#202330',
  success: '#73daca',
  warning: '#e0af68',
  danger: '#db4b4b',
  info: '#0da0ba',
});
